name: Build and Test - Windows

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-2022]

    steps:
      - name: Add Microsoft.VisualStudio.Component.WinXP
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --channelId VisualStudio.17.Release --productId Microsoft.VisualStudio.Product.Enterprise -q --add Microsoft.VisualStudio.Component.WinXP
        shell: cmd

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build - Win32
        run: |
          src\Build_Win32.cmd

